### PR TITLE
Add `@ReactModule` annotation and `NAME` constant

### PR DESCRIPTION
**Pull request by janicduplessis**
## Description

Add `@ReactModule` annotation and `NAME` constant. This will eventually be used by TurboModules annotation processor.

## Compatibility

N/A

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`deviceinfo.d.ts`, `deviceinfo.js.flow`)
* [ ] I updated the dummy web/test polyfill (`default/index.js`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Seems fine - and thank you! - a couple questions:

- when does TurboModules come in and what's the effect? A pointer to a good doc you'd recommend is sufficient, I can read up :-)
- when did this API come into existence? Are we cutting off compatibility to some older react-native versions by adding this? If so which ones?

**Comment by janicduplessis** [comment]
There is some info about it here https://github.com/react-native-community/discussions-and-proposals/issues/40. Basically this enables using TurboReactPackage more easily, it allows loading native modules lazily at the moment they are used in JS.

The annotation class was added in September 2016 so it should be fine.

**Comment by mikehardy** [comment]
Awesome thanks for both bits of info - I'm traveling so please be patient but I'll double check and likely merge and release, next opportunity. I appreciate the help!

**Comment by mikehardy** [comment]
Thanks for your patience! Shaping up a v3 release with most of the backlog now

**Comment by mikehardy** [comment]
@janicduplessis 
The only thing I don't like about this, is that now Android Studio can't find the import or the ReactModule symbol. Is there something we need to also add in build.gradle in order for Android Studio state to be sane again?

**Comment by janicduplessis** [comment]
Hmm that’s strange, it should work fine. Maybe its a cache issue or something? I’ll try to run the sample from the repo to see if I get the issue too.

**Comment by mikehardy** [comment]
Oh it runs fine - as in you can use it in a project that depends on react-native, but in this repo and react-native-localize at least, if you open <library>/android in Android Studio by itself to work on the library, it can't find the symbol. That's puzzling to me

**Comment by mikehardy** [comment]
@janicduplessis I hope you haven't spent much if any time looking yet - it helps to actually have a devDependency on react-native and include it in the build.gradle if you, you know, want Android Studio to have access to symbols you want to use :man_facepalming:  :sweat_smile: 

All good now.

**Comment by janicduplessis** [comment]
Haha I forgot about this. Awesome!!

**Pull request merged**
