### PR TITLE
Refactor device type resolver

### PR DESCRIPTION
**Pull request by andresesfm**
## Description

Refactors the methods used to determine de device type on Android. This allows Android native interoperability (described in the README.md

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Interesting - I'd never thought of that as a use case but I haven't had to handle react-native brown-field apps as of yet, I assume that's the use for you?

Looks sane enough and even without the use case it separates this out as a nice coherent chunk of logic.

How have you tested it?

**Comment by andresesfm** [comment]
Hello, thank you for looking at my PR @mikehardy. We have a "pure" react-native app. Here is the scenario we need this for: We want call `requestOrientation` as the first thing when we create the main activity. This is so the tablet version of the app starts in landscape. 

We tried three things: 1) Doing it in JS but since RN takes a second to launch, we would see portrait execution for a split second. So we went to 2) Doing the check on native, this works well but we logic implemented was different from the one in react-native-device-info.  Finally, 3) We went with your implementation for consistency and it works well but that meant I had to copy-paste the same chunk of code. 

So, this proposed solution would solve all our problems, it means that we can reuse the logic implemented in the library on both native and js without code duplication. As an added bonus, decouples that functionality that does not require `reactContext`, any Context object would do

**Comment by mikehardy** [comment]
That's an interesting problem + solution, I know from work with the splash screen module that yes - there's sometimes quite a long time in native code before JS loads things. Yeah, I think it passes muster just as a nice encapsulation of the logic.

So you tested this on phone and tablet and it looks good to you? Seems like the answer is yes but I want to confirm

**Comment by andresesfm** [comment]
Yes, we have tested on both phones and tablets of different sizes/densities.

**Comment by mikehardy** [comment]
> Yes, we have tested on both phones and tablets of different sizes/densities.

Excellent! merged - I have a couple unreleased changes on master now and hope to get a release out shortly but obviously you're safe in using this now - either depending on the git commit hash (safe + reproducible) or master as you see fit.

Thanks!

**Pull request merged**
