### PR TITLE
chore: convert gradle config to modern style

### PR DESCRIPTION
**Pull request by mikehardy**
this is largely based off personal experience plus a look at react-native-share
Also Obsoletes #484

This is what modern gradle configs look like in modules, and I don't believe this has any compatibility impact. Builds cleanly and runs the example for me

### CODE REVIEW

**Comment by mikehardy** [comment]
@machour with the example pointed to master now (I just rebased this so that change is present on this branch), this is trivial to check out and test

**Comment by mikehardy** [comment]
Sorry - that's not quite true, you'll want to change the package reference in the example to 'github:mikehardy/react-native-device-info#gradle-safeExtGet' then npm install and react-native run-android to test it

**Comment by machour** [comment]
I won't be able to test this soon and I'd hate to slow you down.
I would just advise doing a first release with what have already been merged, then a new release with this change, so that if people start to complain about build problems, we'll know exactly where to look.
Wdyt ?

**Comment by mikehardy** [comment]
I love that idea. I think it's all ready on master for a minor bump

**Pull request merged**
