### PR TITLE
Add android get installer package name

### PR DESCRIPTION
**Pull request by TingC**
## Description

Added `getInstallerPackageName()` that retrieve the package name of the application that installed a package.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`.
* [X] I mentioned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by mikehardy** [comment]
I'd like to stay focused on device information and not worry about packages in this module.

I'm going to close this, however I maintain a different module which can do what you need, here's the exact line even:
https://github.com/mikehardy/react-native-update-apk/blob/master/example/App.js#L170

That module isn't unique either, there are a few that handle all the package details for android

**Comment by mjgallag** [comment]
@mikehardy what's the difference is between including https://github.com/react-native-community/react-native-device-info/pull/344 but not including this?

/cc @TingC

**Comment by mikehardy** [comment]
The difference I was not maintainer then ;-). And what I've seen since taking over the package is that we can try to be all things to all people and not do everything well, or we can stay focused strictly on device info and be excellent at it, while letting other packages that are already doing related work be excellent at that. And I believe there are already packages that handle APK-related things well, like one I also work on, and linked above :man_shrugging: - so, not being obstructive, just trying not to bloat out the package and suffocate under the weight of it

**Comment by mjgallag** [comment]
@mikehardy makes sense to me, thanks for the quick clarification. I just realized #344 was over a year older than this, 2018 not 2019, when I posted I thought it had merged just two weeks before :)

**Pull request closed without merging**
