### PR TITLE
Get charging info for device

### PR DESCRIPTION
**Pull request by dominicrico**
## Description

Fixed issue #387 

**Haven't tested this on a Windows Phone!**

Android and iOS should be good.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅    |
| Windows |    ✅    |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`.
* [X] I mentionned this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by machour** [comment]
As discussed in #387, this introduce a BC break and cannot be merged in 0.x versions

**Comment by adaszyn** [comment]
Hey! Any updates on that? It would be awesome to include `getChargingState` method (or similar) to the library.

**Comment by mikehardy** [comment]
This is obsolete - we have isBatteryCharging and getBatteryLevel now from other work so this should be all handled now

**Comment by mikehardy** [comment]
It's out!

https://www.npmjs.com/package/react-native-device-info/v/1.2.0

**Pull request closed without merging**
