### PR TITLE
Ignore missing permissions in lint, specify minor support library versions

### LINKED ISSUE #325: Lint Error Android Build
## Summary

when running :react-native-device-info:lint I get an error. Originally it was complaining about RNDeviceModule.java overriding or implementing a deprecated API, but I can't reproduce that error. I have attached the lint results print out.

|             |     |
| ----------- | --- |
| Version     | 0.15.2  |
| Affected OS | ?   |
| OS Version  | ?   |

### PR DESCRIPTION
**Pull request by mikehardy**
Took the advice from a comment on the linked issue: https://github.com/react-native-community/react-native-device-info/issues/325#issuecomment-448498293

## Description

Should fix #325

### CODE REVIEW

**Comment by machour** [comment]
Could you add the Changelog entry? We'll be incrementing last digit

**Comment by mikehardy** [comment]
Changelog added, and in further testing I discovered lint gets really mad about support library mismatches, so I had to specify fallback versions for some minor support libraries that matched the main support library version.

That should be backwards compatible as the versions there move in lockstep with the main support library, and we were already relying on either the app to specify it or a version we specified with the previous 28.0.0 version

**Comment by mikehardy** [comment]
Oh, should mention that the test would be to merge the PR (or pull my branch), do a `npm install` in the example directory, then `./gradlew :react-native-device-info:lint`. If you do that in master (before merge) it'll fail, but from my PR branch it passes now.

**Comment by machour** [comment]
react-native-device-info 0.29.1 published 🎉

**Pull request merged**
