### PR TITLE
Adding useFirstInstallTime()

### PR DESCRIPTION
**Pull request by schie**
## Description

Added `useFirstInstallTime()` that simply wraps async function, `getFirstInstallTime()`, into a hook.

_**Note**: The src can be used as a template for wrapping the rest of the async functions into hooks where applicable._

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ✅     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [X] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [X] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! Thanks for proposing this

On the face of it, it seems more complicated than I want, with a new type etc., but I can see how that's attempting to mask the async-ness of the underlying method

Is there anyway to do it such that it doesn't need a new type wrapper (with loading flag) and is just working with a number?

I'm not wise on how hooks work yet so I don't know if this is the normal pattern for handling async in hooks or not, but I'd be happy to read up on it if you can offer a link or two to docs or other examples

**Comment by schie** [comment]
Hi @mikehardy,

Thanks for getting back so quickly.

I don't really have much documentation on why to use the flag itself, but there are a number of other libraries that I've used that use it. The first that comes to mind, is [Apollo's `useQuery` hook](https://www.apollographql.com/docs/react/api/react-hooks/#usequery).

I like the idea of a `loading` field because it lets me know why the value may be `null` and how to handle it (show a spinner, loading modal, etc...) 

With that being said, I can definitely change it to just a simple `null | number`. 

Also, the `loading` flag may not be necessary since it is very quick to fetch that information.

Thoughts?

**Comment by mikehardy** [comment]
yes - there are a range of options, items like that could even be constants with no async to hide. This seems like the same sort of problem I was intending to solve the mirrored zzz() zzzSync() API mirroring, but expressed in hook semantics. Not necessarily bad, I'll follow the link you sent and study a bit

**Comment by mikehardy** [comment]
Ok - I studied up, thanks for the link. I think the pattern is reasonable so I'm okay with adding it like this but I'd like make it generic so that every hook wrapping an async call doesn't need it's own type. Seems like we could have one AsyncHookResult type that has loading then a result that's one of the other types we can return? Does that make sense?

Seperately - I don't want to return nulls, I'd like to stick with the default return values for unknown items which would be -1 at the moment https://github.com/react-native-community/react-native-device-info/blob/master/src/index.ts#L780

**Comment by schie** [comment]
Good idea. 

We could have an Generic type something  like the following:

```ts
interface AsyncHookResult<T>{
  loading: boolean;
  result: T|-1
}
```

So the hook would return `AsyncHookResult<number>`

Thoughts?

If all is kosher, I’ll update with the above.

**Comment by mikehardy** [comment]
I think result is T|-1|false|'unknown' as those are our three default no-answer answers, but otherwise, yes!

**Comment by schie** [comment]
Hi @mikehardy,

Happy Monday!

Should be good-to-go for you.

**Comment by mikehardy** [comment]
That looks pretty sweet and should be a nice template for others to follow if they like. Thanks!

**Pull request merged**
