### PR TITLE
Fix wrong example code of hasNotch() in docs

### PR DESCRIPTION
**Pull request by cereme**
## Description

Fixed issue #843 

Though return type of hasNotch in API table was right, example code was still Promise-based code.

### CODE REVIEW

**Comment by mohak1990** [comment]
Still facing the same issue. Returning promise on DeviceInfo.hasNotch() check and not a Boolean value.

**Comment by mikehardy** [comment]
@mohak1990 you are spamming me with notifications, why? Once is good.

https://github.com/react-native-community/react-native-device-info/blob/master/src/index.ts#L761

Looks good to me? 

https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L88

works?

Suspect every part of your local project, caching, versions etc. `npx react-native-clean-project` if you have to

**Comment by mohak1990** [comment]
Screenshot 2019-10-30 at 12 36 37 PM

**Comment by mikehardy** [comment]
@mohak1990 Pictures aren't really helpful as proof of anything - prefer references to source like I did above, as that allows a collaborator to expand their reference context as much as needed to solve the problem.

I think I found it though - may I infer you are using flow? https://github.com/react-native-community/react-native-device-info/blob/master/src/index.js.flow#L84

Looks like that type was missed. Hit me with a PR and I'll merge it right in with credit for persisting to find this thing!

**Pull request merged**
