### PR TITLE
chore: Update deviceinfo.js entry for xioami mi 8 lite

### PR DESCRIPTION
**Pull request by iamdhj**
## Description

Fixed issue hasNotch() return false on Xiaomi Mi 8 Lite, fix devicesWithNotch config with `DeviceInfo.getModel()`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅    |
| Windows |    ❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`deviceinfo.d.ts`, `deviceinfo.js.flow`)
* [ ] I updated the web polyfill (`web/index.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
@chenpeng1102 this looks fine to me, but you were the original author - seems like your previous xiaomi patch just had a missing space here - does this seem good to you?

**Comment by machour** [comment]
@mikehardy should matching be done without taking account spaces? 🤔

**Comment by mikehardy** [comment]
I contemplated that for a second and thought it was too iffy to suggest. But it does seem like it should work in almost all cases - just if it didn't I think that would be more surprising than case-normalizing. But I don't feel strongly about it at all

**Comment by mikehardy** [comment]
No response from previous author, and my default stance was to merge, this looks good to me...thank you @iamdhj !

**Comment by mikehardy** [comment]
v1.5.1 is live on npmjs.com :rocket:

**Comment by chenpeng1102** [comment]
I am very sorry that I have not seen the message. I tested it on the simulator，is fine 👍

**Pull request merged**
