### PR TITLE
V4 constants

### PR DESCRIPTION
**Pull request by mikehardy**
This is a merge of the work of @acoates-ms @santiagofm and @jensdebergh

You guys have my gratitude for pitching in here

By inclusion it Obsoletes #817 #832 #828 

It's not quite ready yet but you can pull it and test it, I'm going to re-test in a few different ways and re-read before merging and tagging 4.0.1-beta.5

### CODE REVIEW

**Comment by mikehardy** [comment]
That's odd - something is very wrong with the windows build @acoates-ms  ? But I believe I merged your PR into this branch cleanly - normally my git-fu is pretty strong on rebases etc but maybe I messed it up?

**Comment by acoates-ms** [comment]
The github action definition in this PR looks pretty different from the one in my PR.

This appears to be just trying to build the local solution, whereas mine was verifying it in a more complete app.  -- I think if you just copy and paste the action definition I had in my PR it should work for you.  -- May as well verify the more realistic scenario.

**Comment by mikehardy** [comment]
That is unexpected - it's a merge failure, no alteration was intended from your original commit. I'll examine that with an eye towards all other parts of the merge, thanks

**Comment by acoates-ms** [comment]
It might have been like that on my mi initial commit or something. Make sure you merged the whole pr

**Comment by mikehardy** [comment]
@acoates-ms to the best of my knowledge I have merged your proposed github action correctly. I receive the same md5sum on the file in my merged branch vs the branch you made the PR from. So it appears there really is something wrong with it

I don't consider that blocking for thjis PR as it's a new feature but of course I'd like it to work to support windows more reliably, if you could take a look as available

```shell
mike@isabela:~/work/react-random/react-native-device-info (master) % a|grep uum
alias uum='git fetch upstream && git rebase upstream/master'
mike@isabela:~/work/react-random/react-native-device-info (master) % git remote -v |grep upstream
upstream	git@github.com:react-native-community/react-native-device-info.git (fetch)
upstream	git@github.com:react-native-community/react-native-device-info.git (push)
mike@isabela:~/work/react-random/react-native-device-info (master) % uum
Current branch master is up to date.
mike@isabela:~/work/react-random/react-native-device-info (master) % git co v4-constants 
Branch 'v4-constants' set up to track remote branch 'v4-constants' from 'upstream'.
Switched to a new branch 'v4-constants'
mike@isabela:~/work/react-random/react-native-device-info (v4-constants) % git status
On branch v4-constants
Your branch is up to date with 'upstream/v4-constants'.

nothing to commit, working tree clean
mike@isabela:~/work/react-random/react-native-device-info (v4-constants) % md5sum .github/workflows/pr.yml 
76f4d2ab50c66017ab25b801b28a307b  .github/workflows/pr.yml
mike@isabela:~/work/react-random/react-native-device-info (v4-constants) % git remote -v |grep acoates
acoates-ms	git@github.com:acoates-ms/react-native-device-info.git (fetch)
acoates-ms	git@github.com:acoates-ms/react-native-device-info.git (push)
mike@isabela:~/work/react-random/react-native-device-info (v4-constants) % git co acoates-ms/
mike@isabela:~/work/react-random/react-native-device-info (v4-constants) % git co constants2 
Branch 'constants2' set up to track remote branch 'constants2' from 'acoates-ms'.
Switched to a new branch 'constants2'
mike@isabela:~/work/react-random/react-native-device-info (constants2) % md5sum .github/workflows/pr.yml 
76f4d2ab50c66017ab25b801b28a307b  .github/workflows/pr.yml
```

**Comment by mikehardy** [comment]
Nice, CI went green - thanks @acoates-ms

**Pull request merged**
