### PR TITLE
Simplifying hookification and adding use device name

### PR DESCRIPTION
**Pull request by schie**
## Description

- Added `useDeviceName()` that wraps `getDeviceName()`
- Added internal utility function, `useOnMount(...)`,  to simplify the _'hookification'_ (patent pending) of some async functions

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅     |
| Windows |    ✅     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [X] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Nice - this softens the blow of the code multiplier that hooks otherwise is - so now it looks like (whitespace aside) effectively a one-liner to wrap any of the async calls in a hook? And this works for you on firstInstallTime and deviceName in testing?

**Comment by schie** [comment]
Yep! It should be super simple to wrap most of the other async functions. 

There are a few that will require a bit more than the wrapper I made. I’ll work on those soon for another PR.

**Comment by mikehardy** [comment]
Great - merged - it sounds like you have an internal plan for more development, I could release now or wait - I don't believe anyone is waiting for anything and there are no bugfixes queued so I'm inclined to wait unless you need a release for your own purposes with this work included (which would be fine too). 

Cheers

**Comment by schie** [comment]
Waiting is fine with me! I'll probably have another PR out tonight

**Pull request merged**
