### PR TITLE
Adding useHasSystemFeature

### PR DESCRIPTION
**Pull request by schie**
## Description

Added `useHasSystemFeature(feature: string)` that hookifies `hasSystemFeature(feature: string)`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [X] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by schie** [comment]
Not sure why ‘Nuget restore’ failed;  I didn’t touch any of that.

**Comment by schie** [comment]
@mikehardy, @machour, @GantMan, @Johan-dutoit,

Do any of you know how to resolve this check error? 

I'm at a bit of a loss.

**Comment by mikehardy** [comment]
@schie - don't worry about the windows failures, that's github actions in flux. I'll research it separately from review and I consider it non-blocking for now

**Comment by schie** [comment]
@mikehardy,

Happy to help!

**Comment by acoates-ms** [comment]
@mikehardy, turns out the issue was actually related to a broken publish of react-native-windows.  I've published a fixed version of react-native-windows, so the builds should work again.

**Comment by mikehardy** [comment]
@acoates-ms sounds like a fun day - those are always good ones. Thank you sir
@schie thank you as well - merging now...

**Pull request merged**
