### PR TITLE
Export react-native-device-info to be compatible with destructured ES6 imports

### PR DESCRIPTION
**Pull request by Taym95**
## Description

Fixed issue #723

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`deviceinfo.d.ts`, `deviceinfo.js.flow`)
* [ ] I updated the dummy web/test polyfill (`default/index.js`)
* [x] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
I like the idea but I wish this didn't add essentially a duplicate entry for each function. Is there any way (breaking or non-breaking) to do this without duplicating each function entry? Just trying to keep the barrier as low as possible for people that propose PRs - we already have like 5 things we ask people to do :-)

**Comment by Taym95** [comment]
Yeah, I got your point, but unfortunately, this is the only way to implement destructured ES6 imports!

**Comment by mikehardy** [comment]
ok - I will likely merge but I want to think on it just a bit more by looking at other modules to see how they did it (usually I examine react-native-community/netinfo) - maybe there's nothing to be done but maybe there's an organizational trick I/we could use

**Comment by Taym95** [comment]
Yes absolutely, That is exactly what I did, I checked how `react-native-community/netinfo` implemented it.

**Comment by mikehardy** [comment]
Man, I guess it's just verbose then. Some things javascript is great at. Some things, not so much...module systems... :man_shrugging:

**Comment by Taym95** [comment]
Yes exactly, I removed duplicate function implementation, so now contributor can add function to be exported :
```
export function getExample() {
  return RNDeviceInfo.example;
}
```
then add it to default export :
```
export default {
	//other functions
	...,
	getExample
}

**Comment by mikehardy** [comment]
Thanks for your patience! Big refactor and release coming up as a v3, this will be in it

**Pull request merged**
