### PR TITLE
Hooks

### PR DESCRIPTION
**Pull request by magrinj**
## Description

I've add 3 hooks, I made a first PR to know if everything seems good to you, because I plan to add hook for every function

Added: 
- [x] useBatteryLevel() hook
- [x] useBatteryLevelIsLow() hook
- [x] usePowerState() hook

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [x] I mentioned this change in `CHANGELOG.md`
* [x] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [x] I updated the dummy web/test polyfill (`default/index.js`)
* [x] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hmm - looks neat but I wonder about the possible code expansion - will this effectively double the size of the library? We're already starved for maintainers and that's a pile of new code.

Or is this just for events?

**Comment by magrinj** [comment]
@mikehardy In the current case of this PR, I've implemented it just for the events because it's the more common use case for hooks (due to the possible update of the data, and the need of the component to re-render).

It can also be implemented on the other async functions, but you're right that's going to add some code for each function. So, it's lees needed on these functions, because the value is updated just one time. Hook can be created by library users if you want less to maintain.

As an example, each async hook for the other function should look like this:
```js
export function useSerialNumber(): string | null {
  const [serialNumber, setSerialNumber] = useState< string | null>(null);

  useEffect(() => {
    const setValue = async () => {
      const value: string = await getSerialNumber();
      setSerialNumber(value);
    };

    setValue();
  }, []);

  return serialNumber;
}
```

**Comment by mikehardy** [comment]
Ok - I can imagine a good use case here for the events, and I'd be willing to merge that, but holy boilerplate batman, that's a lot of code for a marginal use case on the others, I'd like to avoid that for now. Maybe if we had a code generator or something ;-)

If I were to merge something that was for event only, is this PR already complete, or is there something more you'd add to it before review?

**Comment by magrinj** [comment]
@mikehardy Ok seems good to me, I totally understand ! :) Yes a code generator should be enough for the other ones.

In this PR, I've just put the hook for the events, everything should be good if you want to review it and merge it !

**Comment by mikehardy** [comment]
I'll do a little more local testing, but it looks good to me - thanks for this! I have read all about hooks but not used them yet, appears to be a much easier way to listen for events when consuming the library's API

**Comment by mikehardy** [comment]
released!

**Comment by magrinj** [comment]
Perfect, thanks a lot! :)

**Pull request merged**
