### PR TITLE
fixed hasNotch for nokia devices

### PR DESCRIPTION
**Pull request by sbalajime**
## Description

hasNotch() API has been returning false for my Nokia 6.1 Plus phone. so i changed the model name from '6.1 Plus' to 'Nokia 6.1 Plus' for all Nokia devices
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |
| Windows |    ✅❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I updated the dummy web/test polyfill (`default/index.js`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
It worries me - were you able to test the other models, or just the 6.1 Plus?

**Comment by sbalajime** [comment]
I just tested the 6.1 plus mobile only.

**Comment by mikehardy** [comment]
okay - pending confirmation on the others, can you focus it to just the one you definitely tested? I don't have these devices so I'd like to only change the one(s) we have proof on. But in general thanks a bunch for making the PR, and I'll merge it immediately after the change :-)

**Comment by sbalajime** [comment]
Sure,will do it after few hours.

**Pull request closed without merging**
