### PR TITLE
fix(tvOS): Adding tvOS to isBatteryMonitoringEnabled ignore check

### PR DESCRIPTION
**Pull request by vdimitrovv**
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| tvOS     |    ✅     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I mentioned this change in `CHANGELOG.md`

### CODE REVIEW

**Comment by mikehardy** [comment]
Seems sane enough - this is working well for you?

**Comment by vdimitrovv** [comment]
> Seems sane enough - this is working well for you?

@mikehardy it is as far as I could tell, yes. It wouldn't build on Simulator otherwise.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/releases/tag/v2.0.2

**Comment by mikehardy** [comment]
Thanks for the contribution!

**Pull request merged**
